version: "3.4"

services:

  postgresUserdb:
    image: postgres:latest
    container_name: postgresUserdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgresUserdb
    ports:
      - '5430:5432'
    #volumes:
    #  - /var/local/data/postgresdb:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
